name: Create pull request from issue

on:
  issues:
    types: [opened, edited]

jobs:
  create_pull_request:
    name: Create pull request
    runs-on: ubuntu-latest
    env:
      TITLE: ${{ github.event.issue.title }}
      BODY: ${{ github.event.issue.body }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: |
          echo ${TITLE}
          echo ${BODY}
          echo ${GITHUB_TOKEN}
